import { tools } from "./tools";

export const projects = [

  {
    startYear: 2025,
    endYear: 2025,
    projectType: "Academic",
    title: "High Bridge",
    description: "HTML Band Website",
    longDescription: [
      "This project is a website that I was tasked to build for a fictional band, High Bridge. The website was created as a platform to showcase music, share upcoming events, and connect with the band's audience.",
      "The project tested my skills in web design, responsiveness, accessibility, and cross-browser compatibility. I focused on creating a visually appealing and user-friendly interface that reflects the band's identity and style.",
      "The website features a clean and modern design, a well-designed, accessible sign up form that meets WCAG standards, and a responsive layout that adapts to different screen sizes.",
      "The project was a valuable opportunity to apply my web development skills in a real-world context and create a functional and engaging online presence for a tentative client.",
    ],
    images: [require("../assets/images/projects/high-bridge/1.png"),require("../assets/images/projects/high-bridge/5.png"), require("../assets/images/projects/high-bridge/2.png"), require("../assets/images/projects/high-bridge/3.png"),require("../assets/images/projects/high-bridge/4.png")],
    tags: ["Web", "UI/UX"],
    tryItLink: "https://highbridge.netlify.app",
    github: "https://github.com/clawrenceharris/high-bridge",
    tools: [
      tools.github,
      tools.git,
      tools.css,
      tools.javascript,
      tools.visualstudiocode,
      tools.html,
      tools.sass,
    ],
  },
  {
    startYear: 2025,
    projectType: "Club",
    title: "Pac-Rat",
    description: "Unity Puzzle Game",
    longDescription: [
      "Pac-Rat is a Unity puzzle in which players navigate a maze, strategically rotating and moving board sections to create solvable paths to the exit.",
      "In addition to leading the game design and development process, I also collaborated with the visual design team to ensure cohesive alignment with the project vision. I thoughtfully programmed the core mechanics and user interface, consistently prioritizing scalable design patterns over quick, temporary solutions.",
      "The biggest challenge was level design. The bulk of the design required balancing the constraints and freedoms of each mechanic, and translating them to levels that challenge the player and force them to think harder about their moves.",
      "As the game soon comes to completion, I feel confident in building unique and complex level mechanics that, together, offer a satisfying balance between reward and challenge.",
    ],
    images: [require("../assets/images/projects/pac-rat/1.png")],
    tags: ["Games"],
    tryItLink: "https://pac-rat.netlify.app",
    github: "https://github.com/AACC-Game-Dev-Club/Mouse_Puzzle_Game",
    tools: [
      tools.photoshop,
      tools.github,
      tools.git,
      tools.unity,
      tools.csharp,
      tools.json,
    ],
  },

  {
    startYear: 2024,
    projectType: "Personal",
    title: "Two Dots Clone",
    description: "Unity Puzzle Game",
    longDescription: [
      "Two Dots has remained one of my cherished mobile puzzle games. The premise of the game involves connecting dots of the same color to form squares, which subsequently clears all dots of the same color from the board. My journey with this endeavor began around 2020, but I initially found it too challenging and took a hiatus. However, several years later, equipped with enhanced Unity game development skills and renewed confidence, I embarked on the project from near scratch. This time proved to be a success, as I was able to develop a satisfying product.",
      "In the initial stages of the project, I encountered a challenge with organizing the code effectively, particularly in separating visual components from game logic. To address this, I implemented a customized version of the Model-View-Controller (MVC) pattern, tailored specifically for Unity, which proved instrumental in resolving the issue.",
      "In addition to the Anchor Dots and Blank Dots that are common mechanics in the original game, I also created one more called Clock Dots, offering a new and unique gameplay. Overall, this project demonstrates my game programming and level design skills which continue to strengthen as I continue to work on new additions to the game. ",
    ],
    images: [
      require("../assets/images/projects/two-dots/1.png"),
      require("../assets/images/projects/two-dots/2.png"),
      require("../assets/images/projects/two-dots/3.png"),
      require("../assets/images/projects/two-dots/4.png"),
    ],
    tags: ["Games"],
    youtube: "https://www.youtube.com/embed/R_eFNtPQVJo?si=sMfmIVeU4faImsgTs",
    github: "https://github.com/clawrenceharris/two-dots",

    tools: [
      tools.photoshop,
      tools.unity,
      tools.csharp,
      tools.json,
    ],
  },
  {
    projectType: "Personal",
    startYear: 2024,
    title: "The Desk",
    description: "React Web App",
    longDescription: [
      "The Desk is a personal project inspired by my previous project Binder. I like to describe it as a virtual Desk where students can share and download useful study materials.",
      "The design was my favorite part of the project, as I was able to achieve a smooth and simple feel using a collapsable three column layout. The challenging part would be enhancing the layout to be more responsive, something I am still working to improve.",
      "I used Redux to enhance state management and improve code quality and user experience. This is also my first Typescript project making my code far more maintainable compared to JavaScript.",
    ],
    tryItLink: "https://clawrenceharris.github.io/desk/",
    images: [
      require("../assets/images/projects/the-desk/1.png"),
      require("../assets/images/projects/the-desk/2.png"),
    ],
    tags: ["Web", "UI/UX"],
    github: "https://github.com/clawrenceharris/desk",
    tools: [
      tools.react,
      tools.typescript,
      tools.git,
      tools.css3,
      tools.github,
      tools.redux,
      tools.visualstudiocode,
      tools.firebase,
    ],
  },

  {
    projectType: "Academic",
    startYear: 2022,
    endYear: 2023,
    title: "Binder",
    description: "React Native Study App",
    longDescription: [
      "Binder is a React Native app designed to revolutionize student studying. It simplifies learning, fosters collaboration, and builds friendships. With a focus on simplicity, Binder allows students to concentrate on studies without complexity.",
      "The app facilitates collaborative learning through effortless group formation and management. Powered by Firebase, it delivers real-time functionality for secure authentication and dynamic updates to study materials and messaging.",
      "Leading the UI design, front end and back end development, I crafted a visually appealing and user-friendly experience. Binder intends to enhance the educational journey for students worldwide, embodying collaboration and community.",
    ],
    images: [require("../assets/images/projects/binder/1.png")],
    tags: ["Mobile", "UI/UX"],
    github: "https://github.com/clawrenceharris/Binder",
    tools: [
      tools.reactnative,
      tools.github,
      tools.git,
      tools.redux,
      tools.visualstudiocode,
      tools.firebase,
    ],
  },

  {
    title: "Moons Footwear",
    projectType: "Academic",
    description: "React E-commerce Website",
    startYear: 2023,
    endYear: 2024,

    longDescription: [
      "Moons Footwear is a fictional shoe company, brought to life through an innovative and responsive e-commerce website built in React. As the sole developer behind this project, my goal was to create an immersive online shopping experience that seamlessly blends functionality, aesthetics, and responsiveness.",
      "Moons incorporates a consistent, accessible and responsive design, as well as an intuitive cart management system, and user-friendly checkout process.",
      "By the completion of this project, I took pride in crafting a website that seamlessly integrates functionality and design while prioritizing responsiveness. Moons stands as a testament to my dedication to creating digital solutions that elevate the user experience and demonstrate proficiency in React development.",
    ],
    tools: [
      tools.javascript,
      tools.react,
      tools.figma,
      tools.visualstudiocode,
      tools.git,
      tools.github,
    ],
    tryItLink: "https://clawrenceharris.github.io/moons/",
    images: [
      require("../assets/images/projects/moons/1.png"),
      require("../assets/images/projects/moons/2.png"),
    ],
    tags: ["Web", "UI/UX"],
    github: "https://github.com/clawrenceharris/moons",
  },
  {
    startYear: 2023,
    endYear: 2023,
    title: "Snake 2",
    projectType: "Personal",
    description: "JavaScript & HTML5 Game",
    longDescription: [
      "Inspired by the classic retro Snake game, Snake 2 is a personal project that reinvents the iconic gaming experience with innovative mechanics, unique challenging levels.",
      "Leveraging the State Pattern design, Snake 2 introduces dynamic states for the snake player. Each power-up picked up triggers a shift in the snake's behavior.",
      "While challenging to manage consistent graphics with the Canvas API and maintain website responsiveness, the process only reinforced the importance of web accessibility.  Despite the difficulty, I successfully developed a flexible and responsive grid system, ensuring a seamless gaming experience across various screen sizes.",
      "The incorporation of novel game mechanics and implementation of game desing patterns like the State Pattern for achieving dynamic states gave me the opportunity to showcase my creativity and combine my two passions for game and web development.",
    ],

    images: [require("../assets/images/projects/snake/1.png")],
    tags: ["Web", "Games"],
    tools: [
      tools.html,
      tools.css,
      tools.visualstudiocode,
      tools.javascript,
      tools.git,
      tools.github,
    ],
    github: "https://github.com/clawrenceharris/snake2",
    tryItLink: "https://clawrenceharris.github.io/snake2/",
    youtube: "https://www.youtube.com/embed/G_2CbYHody8?si=VLlRO6N4NjUyFUEz",
  },
  {
    startYear: 2023,
    endYear: 2024,
    projectType: "Academic",
    title: "Atunity",
    description: "UX Case Study",
    longDescription: [
      "This was a UX case study, based on an app called Atunity, a platform aimed at elevating mental health, concentration and overall well-being. The project's core objective was to create an immersive and user-centric experience, offering a curated collection of tracks, playlists, and videos encompassing soothing music, guided meditation, and calming sounds.",
      "The project kicked off with an in-depth exploration of user needs and expectations. I conducted extensive user interviews and gathered insights into their mental health challenges, stressors and aspirations for a wellness app. Based on the gathered insights, I crafted detailed user personas to represent the diverse range of potential users.",
      "Informed by personas, journey maps, storyboards, interviews, paper prototypes, and iterative testing, the Atunity UX case study has resulted in a thoughtfully designed app. This user-focused methodology has laid out the foundation for an app that will remain relevant to its end users.",
    ],
    images: [require("../assets/images/projects/atunity/1.png")],
    tags: ["UI/UX"],
    tools: [tools.photoshop],
    tryItLink:
      "https://www.behance.net/gallery/193988695/Atunity-UX-Case-Study",
  },

  {
    startYear: 2022,
    title: "Blobs",
    projectType: "Personal",

    description: "Unity Puzzle Game",
    longDescription: [
      "Blobs, a personal project developed while learning Unity and C#, showcases my creative problem-solving skills through effective implementation of robust design patterns. The game features levels with different colored slime cubes, challenging players to clear the board by moving and merging them together.",
      "The concept emerged naturally during brainstorming sessions, refined using colored sticky notes. Structuring code to separate visuals from game logic posed a significant challenge, addressed using an MVC approach. Implementing an 'Undo' feature was facilitated by the Command Pattern, ensuring seamless backtracking and codebase maintainability.",
      "Blobs served as a playground for honing my game programming abilities and exploring advanced concepts in software architecture. I'm continuing to implement other features for the game and build engaging and challenging levels.",
    ],
    images: [require("../assets/images/projects/blobs/1.png")],
    tags: ["Games"],
    youtube: "https://www.youtube.com/embed/oYpmDGsfp0Q?si=Fa2SiPeJgJlgkPoO",
    tools: [
      tools.photoshop,
      tools.unity,
      tools.csharp,
      tools.json,
      tools.git,
      tools.github,
    ],
  },
];
